### ISSUE TITLE
Make stats static on unit types instead of on __init__()

### ISSUE THREAD

**Issue by eoriont** [RileyPaddock/space-empires#13]
In your unit type classes (e.g. `base.py`, `decoy.py`), you define all the stats in the __init__ function. You could simplify it a little bit by just defining them outside of the init function, like:
```
class Decoy(Unit):
    attack_strength = 4
```
This would do the same job as what you have now, but use less code (and be more readable)
The __init__ function would then just fall back to the unit init, so it would work!

**Comment by RileyPaddock** [comment]
Thanks, this is really useful and I implemented it on all my units
