### ISSUE TITLE
Function get_movement_phases should be in some technology file

### ISSUE THREAD

**Issue by eoriont** [RileyPaddock/space-empires#14]
You have this `get_movement_phases` function in your `combat_testing_player.py` file. This is a function that you theoretically need to replicate in all of your player-derived classes, since they all have that same progression of movement spaces. To avoid duplicated code, I recommend making a `technology.py` file somewhere and adding methods that relate to technology there.

**Comment by RileyPaddock** [comment]
I made it a method of my player class which all the different types of players inherit from.
