### ISSUE TITLE
Manual Player Combat

### ISSUE THREAD

**Issue by geomeza** [RileyPaddock/space-empires#15]
You manually check your players for combat and your combat function to find it is a little wacky, what you could do is loop through the players units, add them to an array and check pairs in that array to find which two units are on the same space, an alternative would be to loop through your game board and check how many units are on each space and then check if the units are from different players, this will help in the long run if we ever add more than two players, also i think it would just be easier than just checking only two players all the time

**Comment by RileyPaddock** [comment]
I changed the way I check for combat and now it works like this.
