### ISSUE TITLE
You have 3 function in your space empire game which are too long

### ISSUE THREAD

**Issue by C0BBL3** [RileyPaddock/space-empires#17]
The 3 functions I am talking about are your resolve_combat() and attack() in combat_engine.py and check_for_and_initiate_combat() in game.py which should be in combat_engine.py. Try to split up the functions into helper functions and use dictionaries for general board usage.

**Comment by RileyPaddock** [comment]
I broke these functions into helper functions and I use dictionaries for board function already.
