### ISSUE TITLE
Remove a main.py file

### ISSUE THREAD

**Issue by eoriont** [RileyPaddock/space-empires#19]
This is kind of a small thing, but generally the more you call functions from other files in python the harder it gets to work with your code. You will be constantly switching files just to work on one small feature, which is why I recommend not chaining function calls across multiple files, if the functionality is in the last one, if you can avoid it.

The reason I wrote this issue is because you have multiple `main.py` files. You should choose one, copy the code into the `main.py` in the root of your project, and delete the other `main.py`. If you have multiple things you want to test in the `main.py`, they should be small things like, initializing the game with a different dice pattern and adding combat player vs dumb player. Stuff like this is easy to comment out in the entry file, so it won't be mistaken as dead code as the root file basically should hold nothing. After you populate the root `main.py` file, delete `src/main.py`.

**Comment by RileyPaddock** [comment]
I never used the main.py function. It was a remnant from when we first transferred over to repl. I deleted it,
