### ISSUE TITLE
Sort helpers into respective engines

### ISSUE THREAD

**Issue by eoriont** [RileyPaddock/space-empires#20]
I took a look at your `game.py` file and noticed that it is full of all these helpers for generating state, lists of combats, economic stuff, etc. That's awesome, it looks super clean! The only bad part about it is that cramming all those helpers into a single file makes it hard to work on multiple functions at once in that file. We have `economic_engine.py`, `movement_engine.py`, `combat_engine.py`, so you should put all the helper functions into their corresponding engine files, which not only will make it easier to actually implement into the game, but will make each file much more readable.

**Comment by RileyPaddock** [comment]
I moved the unit_state and player_state into the unit.py and player.py files so now only game_state is in game.py
