### ISSUE TITLE
Player tests

### ISSUE THREAD

**Issue by C0BBL3** [RileyPaddock/space-empires#22]
When creating the player's from the list of strategies, don't use strings, use the class itself, for example, you would create the game like so, `Game([CombatStrategy,  CombatStrategy], ...)` or 
```
player_1_strat = CombatStrategy
player_2_strat = DumbStrategy
game = Game([player_1_strat, player_2_strat], ...)
```
I would also make it so you can create as many players as you want, by looping through the given strategies and creating a player from that strategy.

**Comment by RileyPaddock** [comment]
My game works like this now.
