### ISSUE TITLE
P1 and P2 ships

### ISSUE THREAD

**Issue by geomeza** [RileyPaddock/space-empires#5]
self.p1_ships = []
        self.p2_ships = []
        self.p1_ships = [p1_ship for p1_ship in self.units if p1_ship.team == 1]
        self.p2_ships = [p2_ship for p2_ship in self.units if p2_ship.team == 2]

Why do you do this in your code, just delete the empty arrays

**Comment by RileyPaddock** [comment]
My thinking was I have to empty the arrays before I assign new values but yeah that was stupid, thanks for pointing this out.
