### ISSUE TITLE
Get rid of the static variables in your game class

### ISSUE THREAD

**Issue by eoriont** [RileyPaddock/space-empires#8]
There are a couple things like dice rolls and players in the game to name a few, which you manually set either in the constructor of the class or from a different scope right after you instantiate it. (Setting `game.rolls = [1, 2, 3, 4, 5, 6]`)

You should instead make either helper functions or extra parameters in the game init function to set these variables, so in your test files, you can easily change the combinations of players, or dice rolls.

**Comment by RileyPaddock** [comment]
Alright I made it so now rolls and players are attributes and can be changed when you call on the Game class
