### ISSUE TITLE
Your board class does too little.

### ISSUE THREAD

**Issue by C0BBL3** [RileyPaddock/space-empires#9]
You could extend your game board to have all the data in the game ex a ships_dict with every position and every ship in said position a misc_dict with asteroids and planets, and you should also make a planet and asteroid class in the board file as well. the only reason I'm making this issue is that it's only like 20 or so lines long and doesn't really do anything.

**Comment by RileyPaddock** [comment]
I made my board class interact with almost all aspects of the game and store all the objects in the game by location(but not asteroids because we haven't officially added it to the game yet)
